name: Deploy Yii2 app

on:
  push:
    branches:
      - master   # Or change to 'main' as per your repo

env:
  DOCKER_IMAGE: faixan01/yii2app
  BUILD_ID: ${{ github.run_number }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_IMAGE:$BUILD_ID .
          docker push $DOCKER_IMAGE:$BUILD_ID

      - name: SSH and deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull $DOCKER_IMAGE:$BUILD_ID
            docker service update --image $DOCKER_IMAGE:$BUILD_ID yii2app || \
            docker service create --name yii2app --publish 9000:9000 $DOCKER_IMAGE:$BUILD_ID
